version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: kin2
      POSTGRES_PASSWORD: kin2
      POSTGRES_DB: kin2
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  app:
    build: .
    depends_on: [db]
    env_file: .env
    environment:
      DATABASE_URL: postgres://kin2:kin2@db:5432/kin2
      NODE_ENV: development
      PORT: 8080
    ports: ["8080:8080"]
    command: ["npm","run","start:dev"]

volumes:
  pgdata:
