apiVersion: apps/v1
kind: Deployment
metadata:
  name: kin2-workforce-app
  labels:
    app: kin2-workforce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kin2-workforce
  template:
    metadata:
      labels:
        app: kin2-workforce
    spec:
      containers:
      - name: app
        image: kin2-workforce:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: kin2-secrets
              key: database-url
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: kin2-secrets
              key: session-secret
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: kin2-secrets
              key: stripe-secret-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: kin2-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: kin2-workforce-service
spec:
  selector:
    app: kin2-workforce
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer