apiVersion: apps/v1
kind: Deployment
metadata:
  name: kin2-workforce
  labels:
    app: kin2-workforce
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kin2-workforce
  template:
    metadata:
      labels:
        app: kin2-workforce
        version: v1.0.0
    spec:
      containers:
      - name: kin2-workforce
        image: kin2/workforce:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: kin2-secrets
              key: database-url
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: kin2-secrets
              key: session-secret
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: kin2-secrets
              key: stripe-secret-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: kin2-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: logs
        emptyDir: {}
      - name: uploads
        persistentVolumeClaim:
          claimName: kin2-uploads-pvc
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: kin2-workforce-service
  labels:
    app: kin2-workforce
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: kin2-workforce
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kin2-workforce-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - workforce.kin2.com
    - app.kin2.com
    secretName: kin2-tls
  rules:
  - host: workforce.kin2.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kin2-workforce-service
            port:
              number: 80
  - host: app.kin2.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kin2-workforce-service
            port:
              number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: kin2-secrets
type: Opaque
data:
  database-url: # Base64 encoded DATABASE_URL
  session-secret: # Base64 encoded SESSION_SECRET
  stripe-secret-key: # Base64 encoded STRIPE_SECRET_KEY
  openai-api-key: # Base64 encoded OPENAI_API_KEY
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kin2-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kin2-workforce-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kin2-workforce
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80